---
- name: Deploying Book Bot code
  hosts: all
  user: root

  tasks:
  - name: Pull Book Bot repo updates
    git:
      repo: "https://github.com/jansendotsh/discord-book-bot.git"
      dest: "/data/book-bot"
      version: master
      update: yes

  - name: Stop Book Bot daemon
    systemd:
      name: bookbot
      state: stopped

  - name: Delete Docker image
    docker_image:
      name: book-bot
      tag: "latest"
      state: absent

  - name: Building Docker image
    docker_image:
      name: book-bot
      tag: "latest"
      build:
        path: /data/book-bot
        pull: yes
      source: build
      state: present

  - name: Start Book Bot daemon
    systemd:
      name: bookbot
      state: started